from pathlib import Path
p=Path('/mnt/data/v52work/app.py'); s=p.read_text()
# register_school add phone and request table/notification, no code
old='''        school_name=request.form.get("school_name","").strip(); email=request.form.get("registered_email","").strip(); admin_name=request.form.get("admin_name","").strip(); username=request.form.get("admin_username","").strip()'''
new='''        school_name=request.form.get("school_name","").strip(); email=request.form.get("registered_email","").strip(); phone=request.form.get("registered_phone","").strip(); admin_name=request.form.get("admin_name","").strip(); username=request.form.get("admin_username","").strip()'''
s=s.replace(old,new,1)
old='''            sid=conn.execute("INSERT INTO schools(name,registered_email,activation_status,tenant_id,school_code) VALUES(?,?,?,?,?)",(school_name,email,"pending",tenant,code)).lastrowid\n            conn.execute("INSERT INTO users(school_id,tenant_id,name,username,password_hash,role,first_login_required) VALUES(?,?,?,?,?,'admin',1)",(sid,tenant,admin_name,username,generate_password_hash(secrets.token_urlsafe(24))))\n            seed_school_defaults(conn,sid); _security_audit_event(conn,"school_activation_request",f"Requested school activation for {school_name}",sid); conn.commit(); conn.close(); flash(f"Activation requested. School ID: {code}. Tenant ID: {tenant}. An authorized Super Admin must issue the activation code.","success"); return redirect(url_for("activate_school"))'''
new='''            sid=conn.execute("INSERT INTO schools(name,registered_email,registered_phone,activation_status,tenant_id,school_code) VALUES(?,?,?,?,?,?)",(school_name,email,phone or None,"pending",tenant,code)).lastrowid\n            conn.execute("INSERT INTO users(school_id,tenant_id,name,username,password_hash,role,first_login_required) VALUES(?,?,?,?,?,'admin',1)",(sid,tenant,admin_name,username,generate_password_hash(secrets.token_urlsafe(24))))\n            conn.execute("INSERT INTO platform_activation_requests(school_id,status) VALUES (?, 'pending')",(sid,))\n            conn.execute("INSERT INTO platform_notifications(title,message,school_id) VALUES (?,?,?)",("New school activation request",f"{school_name} registered. School ID: {code}. Tenant ID: {tenant}. Email: {email}. Phone: {phone or 'Not provided'}.",sid))\n            seed_school_defaults(conn,sid); _security_audit_event(conn,"school_activation_request",f"Requested school activation for {school_name}",sid); conn.commit(); conn.close(); flash("School registration submitted. Your school is pending activation. You will be notified when an authorized reviewer approves it and sends the activation code.","success"); return redirect(url_for("activate_school"))'''
s=s.replace(old,new,1)
# platform new school: remove generate/send/flash code, create request + notification
old='''            code, expires_at = generate_activation_code(conn, school_id, created_by=session.get('platform_admin_name'))\n            log_audit(conn, "platform_admin", session.get("platform_admin_name"), "onboard_school",\n                      details=f"Onboarded '{school_name}' ({registered_email})", school_id=school_id)\n            conn.commit()'''
new='''            conn.execute("INSERT INTO platform_activation_requests(school_id,status) VALUES (?, 'pending')",(school_id,))\n            conn.execute("INSERT INTO platform_notifications(title,message,school_id) VALUES (?,?,?)",("New school activation request",f"{school_name} was created and is pending activation. School ID: {code}. Tenant ID: {tenant_id}.",school_id))\n            log_audit(conn, "platform_admin", session.get("platform_admin_name"), "onboard_school", details=f"Onboarded '{school_name}' ({registered_email}) — pending activation", school_id=school_id)\n            conn.commit()'''
s=s.replace(old,new,1)
old='''        sent, msg = send_platform_email(\n            registered_email, f"Activate {school_name} on School Result System",\n            f"Your school has been onboarded.\\n\\nActivation code: {code}\\n"\n            f"This code expires {format_dmy(expires_at)} and can only be used once.\\n\\n"\n            f"Visit the Activate School page and enter this code (with admin username '{admin_username}') "\n            "to finish setting up your account.",\n        )\n        conn.close()\n        flash(f"'{school_name}' onboarded. Activation code: {code} (expires {format_dmy(expires_at)}).", "success")\n        if not sent:\n            flash(f"Couldn't email the code automatically ({msg}) — share the code above with the school directly.", "error")\n        return redirect(url_for("platform_schools"))'''
new='''        conn.close()\n        flash(f"'{school_name}' created and placed in pending activation.", "success")\n        return redirect(url_for("platform_activation_requests"))'''
s=s.replace(old,new,1)
# regenerate code no public display
old='''    flash(f"New activation code: {code} (expires {format_dmy(expires_at)}).", "success")\n    if not sent:\n        flash(f"Couldn't email the code automatically ({msg}) — share the code above with the school directly.", "error")\n    return redirect(url_for("platform_schools"))'''
new='''    flash("A new activation code was generated and sent through the configured delivery channel." if sent else "A new activation code was generated, but delivery is not configured.", "success" if sent else "error")\n    return redirect(url_for("platform_schools"))'''
s=s.replace(old,new,1)
# public activate GET message via template only; no need
p.write_text(s)
