from pathlib import Path
p=Path('/mnt/data/v52work/app.py'); s=p.read_text()
# admin_school update query with result toggles
old='''        auth_show_school_name = 1 if request.form.get("auth_show_school_name") else 0\n        auth_branding_enabled = 1 if request.form.get("auth_branding_enabled") else 0\n        auto_teacher_comment'''
new='''        auth_show_school_name = 1 if request.form.get("auth_show_school_name") else 0\n        auth_branding_enabled = 1 if request.form.get("auth_branding_enabled") else 0\n        show_form_teacher_name = 1 if request.form.get("show_form_teacher_name") else 0\n        show_form_teacher_signature = 1 if request.form.get("show_form_teacher_signature") else 0\n        show_principal_name = 1 if request.form.get("show_principal_name") else 0\n        show_principal_signature = 1 if request.form.get("show_principal_signature") else 0\n        auto_teacher_comment'''
s=s.replace(old,new,1)
s=s.replace('''                "auth_logo_opacity=?, auth_logo_position=?, auth_background_style=?, "\n                "auth_show_school_name=?, auth_branding_enabled=? WHERE id=?",''','''                "auth_logo_opacity=?, auth_logo_position=?, auth_background_style=?, "\n                "auth_show_school_name=?, auth_branding_enabled=?, show_form_teacher_name=?, show_form_teacher_signature=?, "\n                "show_principal_name=?, show_principal_signature=? WHERE id=?",''',1)
s=s.replace('''                 show_result_date, auth_logo_opacity, auth_logo_position,\n                 auth_background_style, auth_show_school_name, auth_branding_enabled, school_id),''','''                 show_result_date, auth_logo_opacity, auth_logo_position,\n                 auth_background_style, auth_show_school_name, auth_branding_enabled, show_form_teacher_name, show_form_teacher_signature,\n                 show_principal_name, show_principal_signature, school_id),''',1)
# admin_theme update query
s=s.replace('''        auth_show_school_name=1 if request.form.get("auth_show_school_name","1") == "1" else 0\n        auth_branding_enabled=1 if request.form.get("auth_branding_enabled","1") == "1" else 0\n        conn.execute("UPDATE schools SET theme_preset=?,dashboard_primary_color=?,dashboard_secondary_color=?,dashboard_accent_color=?,dashboard_sidebar_style=?,dashboard_header_style=?,school_tagline=?,result_accent_color=?,result_header_layout=?,auth_logo_opacity=?,auth_logo_position=?,auth_background_style=?,auth_show_school_name=?,auth_branding_enabled=? WHERE id=?",''','''        auth_show_school_name=1 if request.form.get("auth_show_school_name","1") == "1" else 0\n        auth_branding_enabled=1 if request.form.get("auth_branding_enabled","1") == "1" else 0\n        show_form_teacher_name=1 if request.form.get("show_form_teacher_name","1") == "1" else 0\n        show_form_teacher_signature=1 if request.form.get("show_form_teacher_signature","1") == "1" else 0\n        show_principal_name=1 if request.form.get("show_principal_name","1") == "1" else 0\n        show_principal_signature=1 if request.form.get("show_principal_signature","1") == "1" else 0\n        conn.execute("UPDATE schools SET theme_preset=?,dashboard_primary_color=?,dashboard_secondary_color=?,dashboard_accent_color=?,dashboard_sidebar_style=?,dashboard_header_style=?,school_tagline=?,result_accent_color=?,result_header_layout=?,auth_logo_opacity=?,auth_logo_position=?,auth_background_style=?,auth_show_school_name=?,auth_branding_enabled=?,show_form_teacher_name=?,show_form_teacher_signature=?,show_principal_name=?,show_principal_signature=? WHERE id=?",''',1)
s=s.replace('''result_header,auth_logo_opacity,auth_logo_position,auth_background_style,auth_show_school_name,auth_branding_enabled,sid))''','''result_header,auth_logo_opacity,auth_logo_position,auth_background_style,auth_show_school_name,auth_branding_enabled,show_form_teacher_name,show_form_teacher_signature,show_principal_name,show_principal_signature,sid))''',1)
# build result data filter signatures and names
old='''    teacher_signature_user = _signature_user("teacher_signed_by")\n    principal_signature_user = _signature_user("principal_signed_by")\n\n    return {'''
new='''    teacher_signature_user = _signature_user("teacher_signed_by") if (not school or school["show_form_teacher_signature"] if "show_form_teacher_signature" in school.keys() else True) else None\n    principal_signature_user = _signature_user("principal_signed_by") if (not school or school["show_principal_signature"] if "show_principal_signature" in school.keys() else True) else None\n    teacher_name = teacher_signature_user["name"] if teacher_signature_user and (not school or school["show_form_teacher_name"] if "show_form_teacher_name" in school.keys() else True) else None\n    principal_name = principal_signature_user["name"] if principal_signature_user and (not school or school["show_principal_name"] if "show_principal_name" in school.keys() else True) else None\n\n    return {'''
s=s.replace(old,new,1)
s=s.replace('''        "teacher_signature_user": teacher_signature_user,\n        "principal_signature_user": principal_signature_user,\n    }''','''        "teacher_signature_user": teacher_signature_user,\n        "principal_signature_user": principal_signature_user,\n        "teacher_name": teacher_name, "principal_name": principal_name,\n        "show_form_teacher_name": bool(school["show_form_teacher_name"]) if school and "show_form_teacher_name" in school.keys() else True,\n        "show_principal_name": bool(school["show_principal_name"]) if school and "show_principal_name" in school.keys() else True,\n    }''',1)
# platform activation requests route join school
s=s.replace('''def platform_activation_requests():\n    conn=get_db(); rows=conn.execute("SELECT * FROM platform_activation_requests ORDER BY id DESC LIMIT 200").fetchall(); conn.close(); return render_template('platform_activation_requests.html',requests=rows)''','''def platform_activation_requests():\n    conn=get_db(); rows=conn.execute("SELECT r.*,s.name school_name,s.school_code,s.tenant_id,s.registered_email,s.registered_phone FROM platform_activation_requests r JOIN schools s ON s.id=r.school_id ORDER BY r.id DESC LIMIT 200").fetchall(); conn.close(); return render_template('platform_activation_requests.html',requests=rows)''')
# platform notification inbox
insert=s.rfind('\nif __name__ == "__main__":')
extra='''\n@app.route("/platform/notifications/inbox")\n@platform_admin_required\ndef platform_notification_inbox():\n    conn=get_db(); rows=conn.execute("SELECT n.*,s.name school_name FROM platform_notifications n LEFT JOIN schools s ON s.id=n.school_id ORDER BY n.id DESC LIMIT 200").fetchall(); conn.close(); return render_template("platform_notification_inbox.html",notifications=rows)\n\n'''
s=s[:insert]+extra+s[insert:]
p.write_text(s)
