from pathlib import Path
root=Path('/mnt/data/v52work/templates')
# register school phone
p=root/'register_school.html'; s=p.read_text(); s=s.replace('<label>School Email *<input type="email" name="registered_email" required placeholder="School email address"></label>','<label>School Email *<input type="email" name="registered_email" required placeholder="School email address"></label><label>School Phone (optional)<input type="tel" name="registered_phone" placeholder="School phone number"></label>'); p.write_text(s)
# activate pending notice
p=root/'activate.html'; s=p.read_text(); s=s.replace('<div class="form-intro"><h2>Activate Your School</h2><p>Enter the admin username and activation code you were given, then choose a password.</p></div>', '<div class="form-intro"><h2>Activate Your School</h2><p>Activation codes are issued only after an authorized reviewer approves the school.</p><div class="form-notice"><b>Activation code sent</b><br>If your school has already been approved, check the registered email, SMS or WhatsApp channel for the code. If it is still pending, no code has been issued yet.</div></div>'); p.write_text(s)
# teacher RBAC
p=root/'admin_teachers.html'; s=p.read_text(); s=s.replace('<label>Position</label>\n        <select name="position">\n            <option value="">-- not set --</option>\n            {% for value, display in position_choices %}\n            <option value="{{ value }}">{{ display }}</option>\n            {% endfor %}\n        </select>', '<label>RBAC Role</label><select name="rbac_role" required>{% for role in rbac_roles %}<option value="{{ role }}">{{ role }}</option>{% endfor %}</select>'); s=s.replace('<th>Name</th><th>Username</th><th>Email / Phone</th><th>Position</th><th>Status</th><th>Actions</th>','<th>Name</th><th>Username</th><th>Email / Phone</th><th>RBAC Role</th><th>Status</th><th>Actions</th>'); old='<select name="position" style="width:auto; display:inline-block;" onchange="this.form.submit()">\n                        <option value="">-- not set --</option>\n                        {% for value, display in position_choices %}\n                        <option value="{{ value }}" {% if t.position == value %}selected{% endif %}>{{ display }}</option>\n                        {% endfor %}\n                    </select>'; new='<select name="rbac_role" style="width:auto; display:inline-block;" onchange="this.form.submit()">{% for role in rbac_roles %}<option value="{{ role }}" {% if (t.rbac_role or "Teacher") == role %}selected{% endif %}>{{ role }}</option>{% endfor %}</select>'; s=s.replace(old,new); p.write_text(s)
# materials
p=root/'materials.html'; s=p.read_text().replace('<label>File (PDF, Word, PowerPoint or image)</label>\n        <input type="file" name="file">','<label>File (PDF, DOC/DOCX, PPT/PPTX or image) — maximum 1 MB</label>\n        <input type="file" name="file" data-max-bytes="1048576" data-size-message="Learning material must not exceed 1 MB." accept=".pdf,.doc,.docx,.ppt,.pptx,.png,.jpg,.jpeg,.gif">').replace('Uploads are limited to 20MB. For videos, paste a link instead of uploading the file.','Learning material uploads are limited to <b>1 MB</b>. Accepted: PDF, Word, PowerPoint and common image formats. For videos, paste a link instead.'); p.write_text(s)
# staff/student uploads
p=root/'staff_profile.html'; s=p.read_text().replace('<input type="file" name="photo" accept=".png,.jpg,.jpeg,.gif">','<input type="file" name="photo" data-max-bytes="512000" data-size-message="Passport image must not exceed 500 KB." accept=".png,.jpg,.jpeg,.gif"><small>Accepted: PNG, JPG, JPEG, GIF · Maximum 500 KB</small>').replace('<input type="file" name="signature" accept=".png,.jpg,.jpeg,.gif">','<input type="file" name="signature" data-max-bytes="512000" data-size-message="Signature must not exceed 500 KB." accept=".png,.jpg,.jpeg,.gif"><small>Accepted: PNG, JPG, JPEG, GIF · Maximum 500 KB</small>'); p.write_text(s)
p=root/'student_profile.html'; s=p.read_text().replace('<input type="file" name="photo" accept=".png,.jpg,.jpeg,.gif">','<input type="file" name="photo" data-max-bytes="512000" data-size-message="Passport image must not exceed 500 KB." accept=".png,.jpg,.jpeg,.gif"><small>Accepted: PNG, JPG, JPEG, GIF · Maximum 500 KB</small>'); p.write_text(s)
# analytics
(root/'reports_analytics.html').write_text('''{% extends "base.html" %}{% block title %}Reports & Analytics{% endblock %}{% block content %}<div class="page-heading"><div><div class="eyebrow">INSIGHTS</div><h1>Reports & Analytics</h1><p>School-scoped academic, attendance and result insights.</p></div></div><form class="card form-grid" method="GET"><label>Class<select name="class_id"><option value="">All classes</option>{% for c in classes %}<option value="{{ c.id }}" {% if c.id==class_id %}selected{% endif %}>{{ c.name }}</option>{% endfor %}</select></label><label>Subject<select name="subject_id"><option value="">All subjects</option>{% for s in subjects %}<option value="{{ s.id }}" {% if s.id==subject_id %}selected{% endif %}>{{ s.name }}</option>{% endfor %}</select></label><button class="btn">Apply filters</button></form><div class="dashboard-grid"><div class="stat-card"><span>Students</span><strong>{{ students }}</strong></div><div class="stat-card"><span>Active Teachers</span><strong>{{ teachers }}</strong></div><div class="stat-card"><span>Classes</span><strong>{{ classes|length }}</strong></div><div class="stat-card"><span>Current Term</span><strong>{{ term.name if term else '—' }}</strong></div></div><div class="analytics-grid"><div class="card"><h3>Class Performance</h3>{% for r in class_rows %}<div class="analytics-row"><b>{{ r.name }}</b><span>{{ '%.1f'|format(r.avg or 0) }}%</span><div class="bar"><i style="width:{{ [r.avg or 0,100]|min }}%"></i></div></div>{% else %}<p>No result data yet.</p>{% endfor %}</div><div class="card"><h3>Subject Performance</h3>{% for r in subject_rows %}<div class="analytics-row"><b>{{ r.name }}</b><span>{{ '%.1f'|format(r.avg or 0) }}%</span><div class="bar"><i style="width:{{ [r.avg or 0,100]|min }}%"></i></div></div>{% else %}<p>No subject data yet.</p>{% endfor %}</div><div class="card"><h3>Grade Distribution</h3><div class="grade-chart">{% for r in grade_rows %}<div><b>{{ r.grade }}</b><span style="height:{{ [r.n*8,120]|min }}px"></span><small>{{ r.n }}</small></div>{% else %}<p>No grades yet.</p>{% endfor %}</div></div></div>{% endblock %}''')
# timetable generator
(root/'timetable_generate.html').write_text('''{% extends "base.html" %}{% block title %}Automatic Timetable Generator{% endblock %}{% block content %}<div class="page-heading"><div><div class="eyebrow">TIMETABLE</div><h1>Automatic Timetable Generator</h1><p>Generate a conflict-aware timetable, then edit it before publishing.</p></div></div><form method="POST" class="card"><input type="hidden" name="csrf_token" value="{{ csrf_token() }}"><label>School days<select name="days"><option value="5">Monday–Friday</option><option value="6">Monday–Saturday</option></select></label><div class="table-wrap"><table><tr><th>Class</th><th>Subject</th><th>Teacher</th><th>Periods required</th></tr>{% for a in assignments %}<tr><td>{{ classes|selectattr('id','equalto',a.class_id)|map(attribute='name')|first }}</td><td>{{ a.subject_name }}</td><td>{{ a.teacher_name or 'Unassigned' }}</td><td><input type="number" min="0" max="20" name="count_{{ a.class_id }}_{{ a.subject_id }}" value="1" style="width:90px"></td></tr>{% endfor %}</table></div><button class="btn" type="submit">Generate Timetable</button></form>{% endblock %}''')
# activation requests
(root/'platform_activation_requests.html').write_text('''{% extends "base.html" %}{% block title %}Activation Requests{% endblock %}{% block content %}<div class="page-heading"><div><div class="eyebrow">PLATFORM CONTROL</div><h1>School Activation Requests</h1><p>Review pending schools and approve activation securely.</p></div></div><div class="card"><div class="table-wrap"><table><tr><th>School</th><th>School ID</th><th>Tenant ID</th><th>Contact</th><th>Submitted</th><th>Status</th><th>Action</th></tr>{% for r in requests %}{% set s = namespace(name='') %}<tr><td>{{ r.school_id }}</td><td>See Schools</td><td>—</td><td>—</td><td>{{ r.submitted_at|dmy }}</td><td>{{ r.status|title }}</td><td><form method="POST" action="{{ url_for('platform_approve_activation', school_id=r.school_id) }}"><input type="hidden" name="csrf_token" value="{{ csrf_token() }}"><button class="btn btn-small">Approve & Send Activation Code</button></form></td></tr>{% else %}<tr><td colspan="7">No activation requests.</td></tr>{% endfor %}</table></div></div>{% endblock %}''')
# theme result toggles
p=root/'theme_branding.html'; s=p.read_text(); needle='<label>Result Header<select name="result_header_layout">'; insert='<div class="form-grid"><label>Show Form Teacher Name<select name="show_form_teacher_name"><option value="1" {% if school.show_form_teacher_name %}selected{% endif %}>Show</option><option value="0" {% if not school.show_form_teacher_name %}selected{% endif %}>Hide</option></select></label><label>Show Form Teacher Signature<select name="show_form_teacher_signature"><option value="1" {% if school.show_form_teacher_signature %}selected{% endif %}>Show</option><option value="0" {% if not school.show_form_teacher_signature %}selected{% endif %}>Hide</option></select></label><label>Show Principal Name<select name="show_principal_name"><option value="1" {% if school.show_principal_name %}selected{% endif %}>Show</option><option value="0" {% if not school.show_principal_name %}selected{% endif %}>Hide</option></select></label><label>Show Principal Signature<select name="show_principal_signature"><option value="1" {% if school.show_principal_signature %}selected{% endif %}>Show</option><option value="0" {% if not school.show_principal_signature %}selected{% endif %}>Hide</option></select></label></div>'; s=s.replace(needle,insert+needle); p.write_text(s)
# base branding + links + upload validation
p=root/'base.html'; s=p.read_text(); s=s.replace('<div class="brand-mark">◆</div><div><b>{{ school_name }}</b>', '<div class="brand-mark">{% if school_logo_url %}<img src="{{ school_logo_url }}" alt="{{ school_name }}">{% else %}◆{% endif %}</div><div><b>{{ school_name }}</b>',1); s=s.replace('<a href="{{ url_for(\'reports_hub\') }}">▤ <span>Reports</span></a>','<a href="{{ url_for(\'reports_hub\') }}">▤ <span>Reports</span></a><a href="{{ url_for(\'reports_analytics\') }}">▥ <span>Analytics</span></a>'); s=s.replace('<a href="{{ url_for(\'timetable_hub\') }}">▦ <span>Timetable</span></a>','<a href="{{ url_for(\'timetable_hub\') }}">▦ <span>Timetable</span></a>{% if session.get(\'role\') in [\'admin\',\'sub_admin\'] %}<a href="{{ url_for(\'timetable_generate\') }}">⚙ <span>Generate Timetable</span></a>{% endif %}'); s=s.replace('<script>document.getElementById(\'sidebarToggle\')', '<script>document.querySelectorAll(\'input[data-max-bytes]\').forEach(function(input){input.addEventListener(\'change\',function(){var f=input.files&&input.files[0];if(!f)return;var max=Number(input.dataset.maxBytes||0);if(max&&f.size>max){alert(input.dataset.sizeMessage||\'File is too large.\');input.value=\'\';}});});document.querySelectorAll(\'form[enctype="multipart/form-data"]\').forEach(function(form){form.addEventListener(\'submit\',function(e){var bad=false;form.querySelectorAll(\'input[data-max-bytes]\').forEach(function(i){var f=i.files&&i.files[0],m=Number(i.dataset.maxBytes||0);if(f&&m&&f.size>m){bad=true;alert(i.dataset.sizeMessage||\'File is too large.\');i.value=\'\';}});if(bad)e.preventDefault();});});document.getElementById(\'sidebarToggle\')'); p.write_text(s)
# style analytics + brand logo
css=Path('/mnt/data/v52work/static/css/ux-complete.css'); c=css.read_text(); c+='''\n.analytics-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem}.analytics-row{margin:1rem 0}.analytics-row span{float:right;font-weight:800}.bar{height:10px;background:#e8eef7;border-radius:999px;overflow:hidden;margin-top:.45rem}.bar i{display:block;height:100%;background:var(--theme-primary,#1f6feb)}.grade-chart{display:flex;gap:1rem;align-items:flex-end;min-height:150px}.grade-chart div{display:flex;flex-direction:column;align-items:center;gap:.25rem}.grade-chart span{width:34px;background:var(--theme-accent,#7c4dff);border-radius:6px 6px 0 0}.brand-mark img{width:36px;height:36px;object-fit:contain;border-radius:8px}.form-notice{padding:.8rem;border-radius:12px;background:#eef5ff;font-weight:600}.card small{font-weight:600;color:#475569}\n'''; css.write_text(c)
